### ISSUE TITLE
Establish first Cypress component tests

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#100]
We need to start building component test coverage.

In the more mature repo altinn-access-management-frontend,
the component tests are situated inside the frontend repo,
close to the actual components tested.

Thus Cypress must be configured to find and run these tests.

We already have tests set up in components inherited from the AccMan repo,
which at present is at about 50% coverage of components.

```[tasklist]
### Tasks
- [x] set up our frontend repo for integrated Cypress component testing
- [x] test our Cypress component test setup is working locally with script : yarn coverage
- [x] consider the pipeline setup for component testing in AccMan
- [x] test Cypress component test in automatic runs in Github Runner
```

**Comment by Torgeir333** [comment]
Cypress component testing did interfere with previous local E2E testing setup, but on the plus side the 
pipeline run did work, and cypress component tests were performed in the Github Runner environment.
