### ISSUE TITLE
Set up survey system for JWK certificate upload in MaskinportenPage

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#104]
Issue #55 set up a JWK upload page, but the upload process is not surveyed by Redux. This issue is an updated version of #85 

This new issue should address these concerns at a later time,
as this page is part of the second user flow per 13.11.23.

The maskinportenPage uploads a jwk certificate file to BFF. The process works,
and we have added error handling for navigation-away-from-page bug and such.

However, the tight coupling between the upload no.1 of the file from the local computer 
(that the user is using), and the upload no.2 from the browser to the backend BFF,
which is necessitated by a user-friendly page,
is not surveyed satisfactorily at present.

In case the second upload (from browser to BFF) fails, the user will not know.

In development we know that BFF has received the jwk-file, as it appears in the
/wwwroot/ folder.

Possibly we should run a fetchJwkUploadConfirmation API call upon completion of the 
UploadComponent function handleOpprettKnappTrykket() function handleApiUpload(formData);

The UploadComponent could then present the user with a message saying that 
the file was successfully uploaded. 

```[tasklist]
### Tasks
- [ ] establish boolean variables to survey upload process
- [ ] could possibly test this feature by changing URL of call to trigger upload error
- [ ] discuss a confirmation API endpoint with Simen and Rune
- [ ] consider a Redux function for managing this endpoint 
- [ ] implement the dispatch of the fetchJwkUploadConfirmation call
- [ ] present the user with a success or failure text at the bottom of MaskinportenPage
- [ ] could possibly test this feature by changing URL of call to trigger upload error...
```
