### ISSUE TITLE
Move Cypress E2E tests into Frontend repo 

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#105]
The new Cypress Component tests were successful (issue #87 ), 
but the configuration of the E2E
tests needs to be updated. This issue will consider moving the E2E tests into the
Frontend sub-repo, and set up E2E configuration in the same context as component
tests.

The remaining E2E tasks will be transferred to this issue, and completed after/if the
configuration succeeds.

```[tasklist]
### Tasks
- [ ] debug interference from the Cypress Component tests
- [ ] Verify navigation to MaskinportenPage
- [ ] Verify navigation to DirectConsentPage
- [ ] Check filling in of form in CreationPage
- [ ] Submit a CreationPage form and check if new SystemUser appears in OverviewPage
- [ ] Check filling in of form in MaskinportenPage (how to test jwk-upload?!)
```
