### ISSUE TITLE
Track progress on build and run cypress tests in Github Runners in workflow pipeline

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#106]
In issue #29 and issue #100 we demonstrated local build and
local Cypress component testing respectively.

Then lately we demonstrated that the cypress8-triggered workflow 
also can build and run Cypress tests in a Github Runner
(se Repo Wiki for details and link to run results of 10.11.23).

The automatic building and testing of the Frontend is a pre-requisite of
deploying our app to the testing environment, and ultimately, to the
production environment.

This issue aims to track progress on building and testing the frontend app,
as the frontend app bundle is wrapped and served by the BFF dotnet app.

A future goal here is to get a simple version of our frontend app available in the
test environment for use by non-programmers, i.e. testers, designers and product owner.
In order to reach this goal intermediate goals for BFF and True Backend  must be discussed with Simen

```[tasklist]
### Tasks
- [ ] Discuss with Simen the feasibility of getting Frontend app into test environment
- [ ] initiate a broader discussion on the matter
- [ ] plan detailed steps
```
