### ISSUE TITLE
Task Group: Setup dev-test environment for the authentication frontend (BFF-Frontend)

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication-frontend#113]
### Description

The BFF and the authentication frontend will be hosted in the azure container app.  To establish a new environment for the authentication frontend container application, the following must be made available

#### Github Registry
On each merge into main branch, the code must be packaged and published into the github registry as a docker image. The package must be tagged with the github commit sha. This will help us identify the commit associated with the package. A github action must be setup to package the code. Refer Issue https://github.com/Altinn/altinn-authentication-frontend/issues/114

#### Provisioning Azure infrastructure app

All the resources related to the authentication frontend must be grouped under the same resource group in Azure. Following resources will be required for setting up a container application

    - A resource group
    - Container app
    - Container apps environment
    - keyvault
    - Azure Active Directory app to establish integration between github and container app for deployment. Github action will use 
       the credentials from AD app to login to azure (OpenId Connect)    

### Acceptance Criteria

- [ ] Necessary resources are created in azure

```[tasklist]
### Tasks
- [x] Create Dockerfile
- [x] Create Yaml file Workflow for pushing Image to GHCR
- [x] Create Temporary ResourceGroup  authenticationui-dev-rg and environment for deploying Container App
- [x] Deploy Container App using GHCR package with Tag to Temp env
- [ ] Setup postgres db in Temp
- [ ] Setup Environment Variables
- [ ] Write request to Core team for proper environment yml files
- [ ] Setup postgres db in proper AT
- [ ] Ensure the Frontend is in sync
- [ ] Create Keyvault
```

```[tasklist]
### Pull Requests
- [ ] https://github.com/Altinn/altinn-authentication-frontend/pull/121
- [ ] #122
- [ ] #123
```
