### ISSUE TITLE
New iteration of OverviewPage based on new designs of 24.11.23

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#126]
New designs, listed as "Andre utkast 24.11.23" are available in Figma page "Systembruker vise" 
(se links to Figma in Repo Wiki). Also note that another OverviewPageEmpty page might be required
(should perhaps be made into a separate issue).  Also note that no functional notes accompany the designs.

Our live Azure app has at present the following view (screenshot):

![1_OverviewPage_AzureApp_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/20d57bc4-bb79-4413-b342-56e62bbeefcf)

The OverviewPage in Design-24.11.23 is the following: (screenshot)

![1_OverviewPage_Design241123_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/62c91d3d-c808-439a-9498-6d56444a89d7)

The iteration should address (at least) the following changes:

1) Banner title has changed from Systembrukere to Administrere systembruker

2) Nynorsk-tekst are becoming available ---> should be put into language features as we go along

3) The list of SystemBrukere has a sub-header "Du har tidligere opprettet disse systembrukerne",
which has been replaced with "Dine systembrukere"

4) The comment/beskrivelse part of the list of SystemBrukere has been removed

5) The edit functionality has been removed ("Rediger systembruker")

6) The color of the list items seems to have changed from grey to some blue color. 

7) The arrow-down in the list items are in new design not filled, but simple chevrons

Note: Some of these changes are fundamental. For example,  no rationale has been provided for the removal of the comment/beskrivelse. Possibly the changes to the CreationPage could explain this, where the "beskrivelse" input-field
has been removed. This would also trigger changes in the backend etc. But we will leave that to a future iteration.
```[tasklist]
### Tasks
- [x] update banner title
- [x] add nynorsk support
- [x] update sub-header
- [x] remove comment/beskrivelse from list items
- [x] add Rettigheter ikke lagt til to list items
- [x] remove Edit icon
- [ ] set Rettigheter and red color font depending on external boolean variable
- [ ] remove Button from list items
- [ ] set new background color of list items
- [ ] investigate whether CollectionBar supports un-filled chevrons for list item opening
- [x] remove list item orgno: 123456
- [ ] list items should only have title and sub-title but unclear what is what now: firm and product?
- [ ] Mobile view have odd Gå videre functionality that must be removed
- [ ] Title of list items seems to be in fatter font - investigate where this is supported i CollectionBar
```
