### ISSUE TITLE
New iteration of CreationPage based on new designs of 24.11.23

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#127]
New designs, listed as "Andre utkast 24.11.23" are available in Figma page "Systembruker vise"
(se links to Figma in Repo Wiki). Also note that no functional notes accompany the designs.

Our live Azure app has at present the following view for CreationPage (screenshot) :

![2_CreationPage_AzureApp_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/488e35a5-2aa1-4810-b650-7b5090394877)

The CreationPage Design-24.11.23 is the following (screenshot):

![2_CreationPage_Design241123_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/cf1fad80-d5e5-40e2-95a5-80939fc0ffe8)

The iteration should address (at least) the following changes:

1) The "beskrivelse" input-field has been removed ---> this has other implications too, Redux, BFF etc...

2) The input-field labeled "Integrasjonsnavn" has been renamed "Navn på systembruker"

3) The input-field label has been given a QuestionTag implying HELP-functionality ---> future iteration?

4) Nedtrekksmeny has lost its triangle, which has been replaced with a MagnifyingGlass SEARCH functionality
---> does the Digdir DesignSystem cover this scenario: has the design considered what is available?
---> possibly pushed to a future iteration?

5) The buttons have several changes:
a) Moved to the left straight below PullDownMenu
----> this does not seem to consider that the triggering of the PullDownmeny will then push the button out of the way

b) The "avbryt" button is now "naked" ---> there is no rationale about where the user will end up if it is pressed, 
at present in our Azure live app the user is returned to OverviewPage (will leave it as is)

c) Text of "Opprett" button has been expanded to "Opprett systembruker" 
---> does not this button now look strangely bloated?

6) Nynorsk-tekst are becoming available ---> should be put into language features as we go along

7) The new ConfirmationPage obviates the present solution for confirmation on CreationPage

Note: Some of these changes are fundamental. For example, no rationale has been provided for the removal of the comment/beskrivelse. This would trigger changes in the backend API etc. But we will leave that to a future iteration.
```[tasklist]
### Tasks
- [x] change input field Integrasjonsnavn label
- [x] add Bokmaal Language support to CreationPage
- [x] add Nynorsk Language support to CreationPage
- [x] remove input field Beskrivelse
- [x] update confirm button text
- [x] switch confirm and cancel button order
- [x] split content text into two paragraphs
- [x] change appearance of cancel button to nude/quiet
- [x] clean up Redux code for input field Beskrivelse
- [x] plan to remove input field Beskrivelse from BFF DTO integration
- [ ] inquire whether design really intented PullDownMenu items to collide with new Buttons
- [x] investigate future ToolTip support for input field
- [ ] investigate future Search Functionality for PullDownMenu
- [ ] solve Mobile view too-wide-bug of Opprett systembruker button
- [ ] confirm-button should now navigate to new ConfirmationPage
- [ ] old confirmation dialogue should be removed
```
