### ISSUE TITLE
New ConfirmationPage based on new designs of 24.11.23

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#128]
New designs, listed as "Andre utkast 24.11.23" are available in Figma page "Systembruker vise"
(se links to Figma in Repo Wiki). Also note that no functional notes accompany the designs.

Our live Azure app has at present no ConfirmationPage view (but CreationPage has confirmation dialogue, screenshot):

![3_ConfirmationDialogue_AzureApp_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/ffa36458-10c5-4b59-8c23-6d1473194c54)

The new page (screenshot of new design):

![3_ConfirmationPage_Design241123_screenshot_041223](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/5fc5e3e7-2c63-4787-9e9a-54aac84f5765)

Comments upon the new page: there are two buttons, one of which is 
FilledBlue, while the other is WhiteBoxed (but not naked, as in the new CreationPage...
should possibly be made consistent).

Also the ConfirmationPage serves two purposes:
1) it confirms that the SystemBruker has been created
2) it ALSO forks the flow so that the user will have to chose between
a) "Legg til rettigheter"
b) "Legg til rettigheter senere

We have to consider what is the default (and the BrokenFlowScenario: probably this is the "Ingen rettigheter" scenario".

Also note that the "Gi nye enkeltrettigheter" selection will result in the user being transported into the Access Management app. Plans for this are not yet clear. But we need to iterate. Possibly the default/noRight scenario is the one to build for now.

```[tasklist]
### Tasks
- [x] set up basic new page for ConfirmationPage
- [x] set up routing to ConfirmationPage at /confirmation path
- [x] set buttons to both return to OverviewPage
- [x] incorporate new ConfirmationPage in user flow
- [ ] investigate deep link to Access Management app for setting rights (postponed)
```

**Comment by Torgeir333** [comment]
First iteration for ConfirmationPage is ready (Nynorsk-version):

<img width="555" alt="ConfirmationPage_first_iteration_061223" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/0eb83d7e-c6ca-4cf7-8303-45b8fb1c04ff">
