### ISSUE TITLE
New iteration of DirectConsentPage based on new designs of 11.12.23

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#135]
This is the first iteration of the new DirectConsentPage design. 

The new design of 11.12.23 can be found via our Wiki Repo page:
https://github.com/Altinn/altinn-authentication-frontend/wiki/Figma-og-skisser-og-design-og-sånt

Our live Azure app has at present the following view (screenshot):
<img width="1102" alt="DirectConsentPage_PRE_screenshot_030124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/e5ec656c-0492-488d-a2dd-298c9944035e">

<br>

The new design of 11.12.23 (screenshot):

<img width="845" alt="DirectConsentPage_Design-of-111223_030124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/0c3fd040-0f90-4282-a6c3-77da34acb09a">

<br><br>
The new iteration is now online in our Azure app (ghcr image hash ...502):
<img width="955" alt="DirectConsentPage_POST_Azure_screenshot_030124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/234b2256-065e-4ce9-914e-e5828fa60925">

<br>
Future iterations might have to address the following concerns:

1)  No backend support exists for the DirectConsentPage yet,
thus the checkboxes and buttons are not functional
(both buttons will return to the OverviewPage).

2) The checkboxes can be checked, but are not linked to any function yet.

3) The check box label/text seems confusing: what is "data" in this context? 
What is "data for kunder"? Why the distinction?

4) There are combinatorial problems: the user seems able to check one checkbox,
and not the other, then click confirm/"Ja, jeg gir samtykke".  So there seems to be four cases to be handled: 
a) user checks both boxes, then click confirm
b) user check box1, not box2, then click confirm
c) user check box2, not box1, then click confirm
d) user check neither box, then click confirm
----> what is the meaning of all these combinations? how should they be handled?

5) When the user path ends ("Flyt-2"), where is the user supposed to end up? 
In this iteration, as with other pages in the existing app, the user is returned to the OverviewPage. Should there be a new SystemUser in the list there? Or should this kind of user be oblivious to the existence of other user flows such as "Flyt-1"?

<br>

```[tasklist]
### Tasks
- [x] Implement the main text features of the new design
- [x] Implement the new checkboxes from Digdir Designsystem
- [x] Implement Nynorsk and Bokmaal language support
```

**Comment by Torgeir333** [comment]
<img width="785" alt="DirectConsentPage_disabled_ConfirmedButton_040124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/e6d9fffb-1363-414d-b139-03f862b7e609">

**Comment by Torgeir333** [comment]
New Azure app revision online with ghcr hash = ...fc5

**Comment by Torgeir333** [comment]
Until Maskinporten and Backend support for the Frontend solution is available, the DirectConsentPage navigates to OverviewPage upon Confirm, and a mock SystemUser object is posted (Direkte Tilgangsløsning), and appears in the list of SystemUsers in OverviewPage. Note this is a temporary solution.
