### ISSUE TITLE
CreationPage HelpText Symbol First Implementation

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#138]
The design of 24.11.23 has in the CreationPage
included a (?), a question mark in a circle 
signifying a Help-text for the user.

The Designsystem has available a component HelpText
https://storybook.designsystemet.no/?path=/docs/oversikt--docs

This issue will try out this new feature on the CreationPage.

Possibly other pages should also have HelpTexts included in future iterations.

```[tasklist]
### Tasks
- [x] test import of Designsystem HelpText component
- [x] try out placement of HelpText component in CreationPage
- [x] Mobile view pushes HelpText symbol down: should probably be pushed up: fix this
```

**Comment by Torgeir333** [comment]
First iteration of HelpText component

<img width="1047" alt="CreationPage_HelpText_screenshot_050124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/1523052e-eb44-4575-bfc6-baa6f93028d6">

**Comment by Torgeir333** [comment]
<img width="485" alt="CreationPage_HelpText_MobileView_bug_screenshot_110124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/12fb089e-cfb7-4530-9fab-9dc9743cc342">

Bug fixed in CSS. So first iteration is concluded.
