### ISSUE TITLE
First iteration of the new RightsIncludedPage based on Design of 05.12.23

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#142]
A new page in "flyt-1" has been made,
between CreationPage, and ConfirmationPage, in the user flow.

The new design of 05.12.23 
(see Repo Wiki Figma pages linked, and screenshot below),
specifies a list of included rights 
or default rights, included from the vendor (e.g. Visma).

The values listed are fetched from backend,
but BFF so far mocks the values, as deeper layers
are not ready.

The new page includes a new component,
RightsCollectionBar, that is functional,
but it needs further polishing in future iterations.

Screenshot of Design (per 10.01.24):

<img width="790" alt="Design_RightsIncludedPage_screenshot_Flyt1_100124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/ce9d43e4-58c0-4844-aba9-cceaba943c21">

```[tasklist]
### Tasks
- [x] set up basic new RightsIncludedPage
- [x] add Route to new /rightsincluded page path
- [x] add bokmaal and nynorsk language support
- [x] add Redux slice
- [x] add backend (BFF) API call for list (array) of rights
- [x] do initial API call in OverviewPage along with other initial calls
- [x] create new RightsCollectionBar component
- [x] link up RightsCollectionBar to Redux array
```

**Comment by Torgeir333** [comment]
A screenshot of the first iteration:

<img width="903" alt="New_RightsIncludedPage_firstIteration_screenshot_100124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/45c434da-5b60-4778-94b9-f4f5b983ef59">

**Comment by Torgeir333** [comment]
The new page can now be seen in our online Azure app: 
https://authenticationfrontend.mangoflower-96d0829d.norwayeast.azurecontainerapps.io/authfront/ui/auth/overview
