### ISSUE TITLE
Second iteration of OverviewPage rightsArray inside systemUserArray

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#148]
We are planning a new API where BFF provide the current rights for a given systemUser. This issue is the implementation of Frontend anticipation of this new endpoint.

See issue #8 , point 8, with the DTO containing 4 new attributes in addition to Right and ServiceProvider: read, write, sign, read_archive, in form of boolean variables.

In issue #146  we used the  Redux rights-array to mock up
the missing rightsArray inside the list of SystemUsers
on the OverviewPage. The temporary solution can be seen in our live Azure app.

We now want to make each right-bar possible to open, and show the actual actions that are permitted (also see Design sketches of 5/12-23 via Repo Wiki Figma link, the Design ideas seems to be that there should be a CollectionBar inside the CollectionBar).

There should be no edit possibility, as this is the domain of Access Management. We only show rights.

```[tasklist]
### Tasks
- [x] study use of CollectionBar inside CollectionBar
- [x] implement four new read, write, sign, read_archive attributes in Redux
- [x] implement CollectionBar inside CollectionBar first pass
- [x] make custom CollectionBars for Outer and Inner layer of structure
- [x] clean up CSS
```

**Comment by Torgeir333** [comment]
FØR: 
<img width="843" alt="OverviewPage_RightsAsColoredTags_screenshot_FOER_160124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/50bcbffa-d144-4b9e-a944-3049a07f7e1c">

**Comment by Torgeir333** [comment]
ETTER:

<img width="843" alt="OverviewPage_RightsAsColoredTags_screenshot_ETTER_160124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/fc1643c3-2bec-4c6f-bfff-326d22255938">

**Comment by Torgeir333** [comment]
Tilgjengelig versjon ute i Azure container app:

<img width="830" alt="OverviewPage_RightsAsColoredTags_screenshot_Azure_160124" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/b8b25a39-3984-4275-8cf1-50f28c8dbf99">
