### ISSUE TITLE
Upstream of DirectConsentPage and how to get there

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#153]
<b>Background:</b>
On our quest to simplify matters for the users of public IT services we sally forth again.
( https://github.com/Altinn/altinn-authentication-frontend/wiki/Note-on-the-Grand-Context-of-our-New-App#en-brukers-historie )

The simplest way to create a new SystemUser,
is to be sent to the DirectConsentPage.
<b>Here he can create a SystemUser by the click of a single button.</b>

https://authenticationfrontend.mangoflower-96d0829d.norwayeast.azurecontainerapps.io/authfront/ui/auth/directconsent

<b>Q & A</b>
Q How does the USER get to the DirectConsentPage?
A He clicks on the link.

Q Where does the USER find the link to the DirectConsentPage?
A He will find the link in the Altinn Innboks

Q Could not the USER also click a link sent to him on email?
A Yes, but our Russian team is, for some reason, not ready yet with that feature.

Q Could the USER not click on a link on the Fiken webpage?
A Yes, that is a future feature that is much, much better than the Altinn-Innboks-feature,
and it is very tempting to wait until we and Fiken and the Russians are ready to 
implement that solutions. But we will resist that temptation. 

Q Could we not implement both solutions?
A Yes, but one bird in the hand is better than 10 in the bush.

<b>Technical Details:</b>
The link should include an URL parameter in the form of a hash (GUID)
which serve as a unique identifier for the pending request entity in the database.

The link should be put inside a message in the Altinn Innboks. 

The user should RETURN to the Altinn Innboks when he clicks the LEGALISTIC confirm button.

There should be set up an API to create such SystemUser requests in the Altinn Innboks.
Obviously, that API should not be available to the general public, or even our Russian friends.

<b>A user story:</b>
Once upon a time there was a User. He lived in a Beautiful Country that valued the time and efforts of its citizens, so he had heard a rumour that the Altinn Barons had created a new way to sign away his rights.

So User was ready when the Big Company contacted him with an irresistible offer: we can handle your taxes for you (there were very few, and very low taxes in Beautiful Country). Since User preferred to use his time and efforts on other things than taxes, he agreed.

Fine, Big Company said, but we need access to your account at Altinn. We will send you a link.

The very next day User found an email that said that there was a message for him in the Altinn Innboks.
User was annoyed at this, but then he remembered that everybody has to log into Altinn now and then. 

In the Altinn Innboks there was a short message: "Big Company wants to do your taxes. Please click this link." User hesitated. His Mother had always told him not to trust strangers, and do not click on links. But Mother also had said that you have to trust the Altinn Barons. So User held his breath and clicked the link.

User came to a functional, but not very pretty DirectConsentPage. It said that Big Company wanted
access to the following rights:
1) Tax data rights
2) Change your child's name rights

User hesitated about the second right, but if you're in for a penny, you are in for a pound. He pressed the big, blue "I agree" button. 

The computer screen went blank for a second. User thought he heard voices far away. Then he found himself in front of the Altinn Innboks again. Oh well, User thought. Time for some coffee. 

When User arrived with his big jug of coffee back at the computer, there was a new message, confirming that he now had an agreement with Big Company, but that he at any time could click the following link to cancel the SystemUser agreement. 

User thought for a moment. Then he was distracted by something else, and forgot all about the matter.

```[tasklist]
### Tasks
- [ ] we need to investigate how others e.g. Studio creates and sends messages to Altinn Innboks
- [ ] we need functionality at the DirectConsentPage to pick the URL parameter GUID and use in API
- [ ] we need a waiting/spinner functionality at the DirectConsentPage while backend request is processed
- [ ] the actual company name and rights signed away should be listed depending on the API
- [ ] if the User or Big Company has messed up the URL they should be told what they have done wrong
- [ ] we need an URL to send the User back to his Altinn Innboks upon Confirmation (browser function might be suspect, and we do know who the logged in user is)
```
