### ISSUE TITLE
The DirectConsentPage should be a one click stop

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#154]
We will iterate over the DirectConsentPage again,
now with the aim of making it a one-click-stop,
for legal reasons,
but with listing of Rights signed away,
for legal reasons.

The RightsIncludedPage will be in the pattern followed:

<img width="853" alt="DirectConsentPage_only_one_button_asOnRightsIncludedPage" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/404cd288-5b14-4c9a-8bb9-059d73f4b3fc">

```[tasklist]
### Tasks
- [x] Transfer data structure of RightsIncludedPage to new DirectConsentPage
- [x] Transfer graphical feature of RightsIncludedPage to new DirectConsentPage
- [ ] polish the CSS as the pages differ slightly
```
