### ISSUE TITLE
Chore: refactor rtk slices

### ISSUE THREAD

**Issue by mgunnerud** [Altinn/altinn-authentication-frontend#159]
### Description

In the current implementation, each page has a corresponding rtk slice. Since most pages need to load the system user array, they will all call the overview slice to load this list. Instead, slices should handle a single resource each; one slice for systemuser, one slice for vendors etc. This way several pages can use the systemuser slice, and we need less slices in total.

### Tasks
- [x] use RTK Query or consider changing to tanstack query
- [x] refactor slices; remove unused slices. 
- [x] remove tanstack/query package (find another way to load local resource files)
- [x] connect to the PUT and DELETE systemuser endpoints
