### ISSUE TITLE
Create a Consent Like creation page for system user

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#17]
### Description

One goal for the new front end is to improve the onboarding of new customers for system vendors like Fiken or Visma. 

One option to do this is to create a consent-like view that system vendors can link to to make a "one-click" creation of a new system user connected to a specific system vendor

This view should contain the following.

Title with "Create data system integration"    (UX needs to finalize this
Description text with clear information that Vendor X wants to create a system user for the specific reporter. 

"Fiken AS ønsker å opprete en systemintegrasjon for systemet Fiken Økonomi for selskapet  Pølsebu AS"

It should list the Access Groups requested for Pølsebu AS 

"Fiken AS ber om tilgangsgrupper blir gitt til systemet. Tilgangsgruppene vil gi systemintegrasjonen rett til å aksessere digital tjenester på vegne av Pølsebu AS"

Tilgangsgruppene er

- MVA (se tjenester)
- Sykemelding (see tjenester)

Innholdet i tilgangsgruppene kan endre seg hvis nye tjenester for områdetet blir tilgjengelig. 

Tilgangsgruppene kan fjernes når som helst senere fra Altin profil

This is just a sketch based on consent page to give an idea
![image](https://github.com/Altinn/altinn-authentication-frontend/assets/13309071/3b6b9ea8-276e-4cba-9db4-3b9dc14b453f)

### Additional Information

The process to send the user to this would probably be one of two options

#### URL with all information

In this scenario, the system vendor will redirect the user to the System User creation consent page with URL params for System Vendor, System Name, ConsentDescription, requested access groups

#### Pre registration of request

This is similar to consent. The system vendor needs to to an API call to create a system request with information about system, system vendor, access group, reporter ++ and use the requestID as reference in url

### Tasks

- [x] Create mock page DirectConsentPage as a first version based on OverviewPage and CreationPage
- [x] DirectConsentPage is now reachable from repo wiki page link
- [ ] Create a route for consent like system creation
- [ ] Create a View with configurable text. First version will just be used for concept discussions

**Comment by Torgeir333** [comment]
Issue #47 
improve the graphics in the second iteration of this page.
