### ISSUE TITLE
Create System User creation  page

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#19]
### Description

We need a view that allows the user to create a system user and connect it to a system vendor

![image](https://github.com/Altinn/altinn-authentication-frontend/assets/13309071/2c772e51-0cd0-4b70-87ba-9406006d445e)

### Tasks

- [x] Create mock view that can be opened from #14 
- [x] rename and reorganize underlying components of CreationPage
- [x] add input boxes
- [x] add multi selection
- [x] add CSS
- [x] add buttons
- [x] iterate CSS to get closer appearance to view sketch above
- [x] add link to get to new CustomCreationPage

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Torgeir333** [comment]
The new CreationPage is now reachable from the OverviewPage. 

Note that input boxes, multi selection and CSS is still missing.

**Comment by Torgeir333** [comment]
The first iteration of CreationPage now leaves the page prettier and healthier.

**Comment by Torgeir333** [comment]
The first 3 iterations of this page are finished. 

The Redux core will be treated in another issue.

**Comment by Torgeir333** [comment]
The fourth iteration is now in repo master, thus superceding this issue.
