### ISSUE TITLE
Feature: Functionality for managing system users for organizations

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#2]
### Description

Organizations will get a new system user functionality to handle machine-to-machine communication in Norway. 

A SystemUser is an entity in Altinn that can be rights through delegating access groups or single rights to it. 

A SystemUser have the following attributes

- GUID
- Name
- Description
- CreatedType
- DelegatedAccessTo

### In scope

The following views are relevant to this.

### System Users Overview

A view where an organization has listed all their system users. 

It will probably be some list with important stuff like

- Name
- ControlledBy 
- Create

![image](https://github.com/Altinn/altinn-authentication-frontend/assets/13309071/9732fe4f-d44d-40a5-8091-6fa91e5481d5)

### Creation of System Users

From the overview page, creating a new system user should be possible.

- It is possible to set a name and description. 
- It should also be possible to connect the System User to a specific system provided by a vendor. 

There will be a system register for vendors.  If not selected anything, the system user will only be available for Maskin Porten Integration, owned by the same entity that created the system user. 

### Consent-based system user creation

One important aspect of the new solution should be that system providers can onboard new customers with the help of consent-based system creation.

With the help of a pre-defined request or a URL with parameters (to be decided) a system user can be created, an this system user is defined to be used by the system vendor.

TODO: How the rights should be delegated.  

### Out of scope

Backend functionality is described here

https://github.com/Altinn/altinn-authentication/issues/232

### Additional Information

Final concept is not yet landed. Described here 

https://github.com/Altinn/altinn-authentication/issues/200

### Tasks

- [x] #15
- [x] Implement Proxy for System users list in BFF
- [x] Create Functionality for CRUD operations for system users

- [x] Create tool for

**Comment by ekorra** [comment]
Løst som del av https://github.com/Altinn/altinn-authentication/issues/331
