### ISSUE TITLE
Task: Infrastructure for Authentication UI Frontend in AT21

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication-frontend#202]
### Tasks

- [x] Setup the Authentication.UI Frontend with BFF as a Container App:
    - [x] Setup Resourcegroup 
    - [x] Setup Environment for Container App
    - [x] Setup the actual Container App for the Authentication.UI Frontend and BFF
- [x] Setup Postgres Flexible Server with IP firewall:
     - [x] Open Postgres firewall for Developer VM for Authentication Team
     - [x] Open Postgres firewall for the Authentication Component in the AKS
- [x] Setup within existing Azure Keyvault for Platform the following Secrets: ( should be similar setup as for Access Management)
     - [x] Admin user for Yunicle running MigrationScripts. secretname = PgMigrationAdminConnection, value= connectionstring for the postgres_migration_admin user
     - [x] User for running normal NpgSql queries: secretname = PgSqlUserConnection, value = connectionstring for the platform_authentication user
- [x] Setup new Azure Keyvault for the Container App for access to Application Insights within the Resource group for the Container App

**Comment by simen-rekkedal** [comment]
PostgreSqlSettings--AuthenticationDbAdminConncetionString putte inn dagens [altinn-at21-kv.vault.azure.net/secrets/PgMigrationAdminConnection](http://altinn-at21-kv.vault.azure.net/secrets/PgMigrationAdminConnection)

PostgreSqlSettings--AuthenticationDbUserConncetionString putte inn dages [altinn-at21-kv.vault.azure.net/secrets/PgSqlUserConnection](http://altinn-at21-kv.vault.azure.net/secrets/PgSqlUserConnection)
