### ISSUE TITLE
Create System User List API in BFF

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#22]
### Description

We need one API in the backend to list system users for a given party in BFF.  This will be consumed by the overview page. 

### Additional Information

The suggested model for the system user will be

{
  "id": "2334-34545-2-324-2-2" ,
  "Title": "Vårt regnsaksystem",
  "Description": "Koblet opp mot Visma. Snakk med Pål om abonnement",
  "SystemType": "534-ADF-SF",
  "Created": "2023-09-12"
}

### Tasks

- [x] Create SystemUser controller in the backend
- [x] Create List Method
- [x] Create System User service with a list method
- [x] Create System User client Mock that has partyLogic (able to differentiate test data based on party) 
- [x] Create System Users mock data 

### Acceptance Criteria

- [x] BFF exposes an endpoint for listing system users
- [x] Mock data is available to use when developing frontend

**Comment by simen-rekkedal** [comment]
This Issue overlaps with Issue #23 . The SystemUser Crud API, services etc in the BFF is nearly finished.
We should close this issue, and maintain the final tasks in issue 23.
