### ISSUE TITLE
Create CRUD API for SYSTEM users in BFF

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#23]
### Description

We need CRUD API for system user 

### Additional Information

We need to authorize access to this functionality. But this will be done on the component level. BFF API will not authorize that user to do this. 

Systemuser DTO object from BFF API

```json

{
"id" : "37ce1792-3b35-4d50-a07d-636017aa7dbd",
"integrationTitle": "Nytt regnskapsystem",
"description": "Systemet som vi har kjøpt hos Visma. Kai og Guri vet alt om dette systemet.",
"productName": "Visma Skatt",
"SupplierName":  "Visma AS",
"SupplierOrgNo": "889234892"
"ownedByParty": 234654,
"systemUserCreated": "2023-01-01"
}

```

### Tasks

- [x] Create API to create a system user
- [x] Create API to Get system user
- [x] Create API to update system user
- [x] Create API to delete system user
- [x] Create Mock method in SystemUser client for the above. 

See below for model

#22 

### Acceptance Criteria

- [x] There exist an API that Frontend can call to create a system user
- [x] There exist and API that frontend can call to get a system user BY ID
```[tasklist]
### Tasks
- [ ] The Fronend, BFF and Authentication Component with Database should be in sync with Dto to Model mapping
```

**Comment by simen-rekkedal** [comment]
We leave the Mock Data and Integration Tests to issue #25 .
We leave the creation of Client Integration to issue #69.
