### ISSUE TITLE
Feature: User can administrate a system user for a specific fag system in altinn portal

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication-frontend#257]
### Description
The user can manually create a system user for a specific fag system in altinn portal.

### Actors

- Organisational User : A private person login to altinn and representing organisation

### Required Roles

- Tilgangstyrer gives the person right to create system user
- Roles that the "fag system" require

### User Interface
Administrate access page is the new page in authentication frontend in altinn 3. This page makes it possible to create/edit/delete the system user. 

1. Click on the create sytem user button which presents the interface to write a user name and choose a fagsystem. Once they are filled, the user goes to the next page where the rights for the system that are predefined by the fagsystem is seen. The user can now choose to either delegate the rights and create the system user or cancel the process. If the user chooses to create, the system user is created and necessary rights are delegated.
2. List of existing system users is listed
3. Click on an existing system user and is possible to edit system user name
4. Click on an existing system user and is possible to delete a system user

The wireframes can be found here https://www.figma.com/file/qWEscJDVrA2gDP6oTI4Dfm/Team-Tilgangsinfo?type=design&node-id=30-39316&mode=design

### Validations

- TBD

- Do we have any rules on system user name?
- When is it possible to delete
- Is it possible to add/remove rights for an existing system (deliverable in later milestone, not now)
	
### Api Integration

- BFF calls resource register to get the resource name, description https://github.com/Altinn/altinn-authentication-frontend/issues/193
- BFF calls access management Api to check if the user has required single rights to be delegated to system user. 
- BFF calls system register api in authentication to list all the registered systems
- BFF calls system user api in authentication to save the system user.
- BFF calls the new endpoint in authorization api to check if the user has the required rights that he is delegating to the system user
- BFF calls new endpoint in access management to save delegations to the system user id
- BFF calls new endpoint in access management to retreive delegations to the system user id

### Acceptance Criteria

- [ ] "Create system user" link/button is visible to the User with tilgangstyring role for org
- [ ] An organisational user is able to select a fag system
- [ ] All registered_systems that are not deleted and should be visible are listed in the "create system user" page
- [ ] It's possible to enter search text in fagsystem to limit the list based on search text
- [ ] Limit on number of characters for system user?
- [ ] It should not be possible to edit the predifend rights
- [ ] User with tilgangstyring for organisation is able to create a system user
- [ ] User has the necessary single rights to be delegated to the system user.(Delivery 1, it will be extended to tilgangspakke etc in later deliveries)
- [ ] List of created system users will be sorted based on date in descending order
- [ ] User is able to edit a system user
- [ ] User is able to delete a system user
- [ ] User is able to search fagsystem from the fagsystem dropdown when creating a system user
- [ ] The first 5 best matches are listed on search
- [ ] How many characters trigger the search?
- [ ] User is able to list rights of a selected system user

```[tasklist]
### Tasks in Authentication Repo
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/193
```

```[tasklist]
### Tasks in Authentication-Frontend Repo
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/299
- [ ] BFF calls access management Api to ensure that the logged in partyId is an organisation and not a private person
- [ ] BFF calls system register api in authentication to list all the registered systems (gjort, finn tasken)
- [ ] BFF calls system user api in authentication to save the system user.
- [ ] BFF calls new endpoint in access management to save delegations to the system user id ( blocked, waiting for AM to create the endpoint )
- [ ] BFF calls new endpoint in access management to retreive delegations to the system user id ( på overview page ) ( venter litt med denne )
- [ ] It's possible to enter search text in fagsystem to limit the list based on search text (frontend Martin)
- [ ] Limit on number of characters for system user is 255, communicate to the Vendors as a Spec
```

```[tasklist]
### Test
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/312
```

**Comment by ekorra** [comment]
Løst som del av https://github.com/Altinn/altinn-authentication/issues/331
