### ISSUE TITLE
Information given should be stored in Redux State

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#28]
The CreationPage now has input information that could have been used to send a POST request to the backend (or BFF in our case). However, that is not the React Way.

Redux is the central store of information in our app. Redux is supposed to be the final arbiter of truth. So it holds the correct State of our app.

The graphics of our app should not be updated depending on API calls. The frontend should REACT to changes in the Redux State. Thus the name of React.

Thus we need to set up ways to send the input information to the Redux State, and the element components (such as buttons, headings, text, input boxes, or whole complex components of many elements) should update automatically.

As a bonus asynchronous operations are also easier and safer. It is Fire & Forget.

Furthermore, all API calls returns should end in the Redux State. 

As an additional bonus, since there is a central store of information, this information can easily be visualised by tools such as Chrome DevTools.

However, there is a cost of this system, of course, which is the handling of the central core of Redux called Store, the input and output of so-called reducers, which are infamous for being hard to comprehend initially.

But in some ways it is simple: Think of the information of our app as a CAKE. The cake can be split into SLICES, so you can eat your slice in peace from the other pieces.

We aim to first build a simple CreationSlice and then incorporate it into the full State or Store (here the cake analogy breaks down, as one can visualise the half-eaten slice being crammed into the cake again, but then again, an analogy always breaks down).
```[tasklist]
### Tasks
- [x] reform userInfoSlice
- [x] create creationPageSlice
- [x] populate CreationSlice with initial information (initial state)
- [x] create input channels to our CreationSlice (reducers)
- [x] use the reducers to populate our slice with information from CreationPage input boxes
- [x] test the central stores ability to display the CreatePage input information
- [x] fetch information from the Central Store in OverviewPage list
- [x] prepare for POST request to BFF using Redux postRequest functions
- [x] test POST request to BFF by GET request from BFF using fetchRequest functions
- [x] redux post function delivers real values from creationPage to BFF
```

**Comment by Torgeir333** [comment]
Our app can now store information from the CreationPage to Redux global State, and fetch information about the new systemUser in the OverviewPage list.

**Comment by Torgeir333** [comment]
<img width="1036" alt="OverviewPage_screenshot_210923_afternoon" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/7f4f983c-8ffb-41fe-9e2a-07eed2816a69">

**Comment by Torgeir333** [comment]
The Redux system now has had its first full iteration, with the values entered into CreationPage being available at the main OverviewPage as a new SystemUser (see issue #77 )
