### ISSUE TITLE
Set Vite Build configuration both in frontend and bff

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#29]
Altinn is using Docker images for deploying software to production in the Azure Kubernetes clusters (see Docs).

The Docker build process has 3 phases (see Dockerfile):

1) Frontend is built to a javascript bundle, plus css and svg images, "inside" a temporary node:alpine image
2) Bff is built to a temporary Microsoft  sdk:alpine image
3) The two images are combined into an aspnet:alpine final image

That is, the frontend is not contributing an image, but only generated bundle files. 

That is language files (from /localisations/, no_nb.json, no_nn.json, en.json), a manifest.json file, and the real assets inside the /assets/ folder.

Schematically, bundle.js, bundle.css, and bunch of .svg image files. These will be served by the final dotnet app upon requests for the html-file to the HomeController.

The frontend asset files are generated by a build script defined in the /frontend/package.json, 
which is triggering Vite build.

The Vite program will in this case build assets to the /dist/ folder, 
depending on the vite.config.js specifications.

These specifications actually specify the Rollup build tool, 
under the key rollupOptions, which again specify an 
input entrypoint.js (from which the dependency paths are built),
and an output specification.

I will in the following suggest we temporarily specify the file names as:
1) assets/authfrontend.js
2) assets/authfront.css

These filenames will also need to be specified in the dotnet app, that is, in production, 
but not in development, where the dotnet app is only interacting with the Vite server.
```[tasklist]
### Tasks
- [x] edit vite.config.js
- [x] modify dotnet app code for serving bundle.js bundle.css and bundle images
- [x] test build process locally
- [x] set up workflow pipeline to produce bundle and assets in Github Runner
```

**Comment by Torgeir333** [comment]
The frontend "bundle" can now be built both locally (to /dist/ folder), 
and in the Github Runner,
using the .github/workflows/frontend_build_and_cypress.yaml
file.

The pipeline is triggered only by a git push to the branch cypress8.



See PR #103
