### ISSUE TITLE
Keep React Frontend app and BFF app communication in sync

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#34]
A common problem in software development is lack of clarity at the interface between systems. 

In our case we have a BFF app running as a Backend-for-Frontend 
to serve API calls from the React frontend app. 

It is important that the interface between frontend and BFF is clear to all 
interested parties. Also see issue #7 and issue #8.

Today, 29.09.23, the two apps are now running and communicating, 
see README documentation in sub-repos and main repo.

We intend to keep the two apps in sync, to avoid future problems.

```[tasklist]
### Tasks
- [x] Write detailed How-to-run-apps READMEs of sub-repos and main repo.
- [ ] Maintain documentation on how to keep apps running and communicating
- [x] Update repo wiki page list of links to 5 pages per 06.10.23
- [ ] Update Swagger information continously
- [x] Updated repo wiki page list of pages: 4 pages and 1 inactive per 09.10.23
```

**Comment by Torgeir333** [comment]
The 4th of October Simen and Torgeir had a long meeting on the topic of API calls, and how to keep Swagger documentation, Issue-documentation (#8 ), and Wiki-documentation in sync. 

The meeting also resulted in a drastic simplification of the userInfo API call, and the deprecation of the fetchReporteeInfo API call (see issue #8 ).

**Comment by Torgeir333** [comment]
02.11.23 update: Simen has added a new endpoint for software system vendors that will be used to populate the pull-down menu in the CreationPage (see issue #94 )

The new endpoint is available in both Swagger and in issue #8.

**Comment by Torgeir333** [comment]
09.11.23 The pull-down API now works. Possibly the DTO should be modified to include an "empty" first object,
so that the pull-down menu is pre-selected with "nothing" (or, not pre-selected with a firm's software).

**Comment by Torgeir333** [comment]
The frontend repo README is lagging in its quality. The How-to-use information should be updated in light
of the new processes added since the last update (see Repo Wiki, which is updated more easily and more frequently).

**Comment by Torgeir333** [comment]
The cleanup after the new designs of 24.11.23 broke a lot of API,
is now mostly done (and some APIs simplified) both in BFF and Frontend.
