### ISSUE TITLE
Page for creating Altinn Integration in Maskinport

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#38]
### Description

For an organization that does not want to use a system provider to integrate with API they need to create their own integration in Maskinporten of the Altinn Type

This is normally done in MaskinPorten Admin.  To prevent the need for end users to use Maskinoporten Altinn will add a new page where users can set up integrations in Maskinporten. 

This option will be available from the Create System user page

## Update System creation page 

#19 

![image](https://github.com/Altinn/altinn-authentication-frontend/assets/13309071/25ae6cb4-b457-428f-abb0-dc3a482a5390)

## Page for maskinporten integration admin

![image](https://github.com/Altinn/altinn-authentication-frontend/assets/13309071/085e4772-0384-4823-b010-807cd1734734)

```[tasklist]
### Tasks
- [x] first version of the page is online
- [x] first version is linked up to link in repo wiki
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/54
- [x] MaskinportenPage is now third in main user flow, after CreationPage (see repo wiki)
- [x] improve styling of page
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/85
```

**Comment by Torgeir333** [comment]
Issue #104 will track progress on surveying upload of JWK file
