### ISSUE TITLE
Task: 9.11 Setup the content in the appsettings.json files, program.cs and other integration wiring

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication-frontend#41]
The AuthenticationFrontend BFF needs a set of configurations to integrate and run.
During Development it is through local.altinn.cloud

1: See https://github.com/Altinn/app-localtest/tree/AuthFrontLokalTest for changes needed in local-test to run the BFF locally.
  : Need to edit the config file in the loadbalancer to forward the correct route
  : Run the loadbalancer in Docker,
  : Run the BFF and local-test in their local folders with dotnet run
  : Run the vite server for the Frontend in it's local folder with yarn start
2: In progress, see "MangoFlower"...
3: Not started yet.

```[tasklist]
### Tasks
- [x] 1: developer env with appsettings.json, frontend and localtest local.altinn.cloud
- [ ] 2: integration test env, TT02 etc. See also Issue #66 
- [ ] 3: production ready environment settings. See also Issue #66 
```
