### ISSUE TITLE
CreationPage Iteration4

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#46]
New development after meeting with Maskinporten has resulted in a new sketch for the CreationPage (from altinn-authentication: https://github.com/Altinn/altinn-authentication/issues/331)

This issue builds on previous 3 iterations in issue #19 

![NyIterasjon_CreationPage_091023](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/61883a39-2024-4735-873f-b94baa4d7479)

```[tasklist]
### Tasks
- [x] reorganize columns of page
- [x] reorganize text of page
- [x] reorganize links of page
```

**Comment by Torgeir333** [comment]
The fourth iteration of the CreationPage is now in repo master branch, looking like this:

<img width="551" alt="FjerdeIterasjon_CreationPage_091023" src="https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/b656a45f-153a-45fc-bfe5-44a4cdf3e0d0">

**Comment by Torgeir333** [comment]
The new user flow has been documented in the repo wiki.
