### ISSUE TITLE
Initial setup of Authentication Frontend repo

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#5]
### Description

We wish to build a frontend for authentication with similar solutions as access management
(https://github.com/Altinn/altinn-access-management-frontend), to keep a consistent profile for the two authorization teams.

### Additional Information

We plan to transfer much code from the access management solution, and modify it to our needs.
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/1
- [x] Transfer code
- [x] Modify code to run in new repo
- [x] Test code by running on Mac and PC
```

**Comment by Torgeir333** [comment]
The frontend sub-repo is now well established.
