### ISSUE TITLE
Add a functional button for upload of file on Maskinporten Adm page

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#54]
Our Maskinporten Administration page should provide a feature
for uploading a certificate. The intention is to provide an easy way
to link up your own service provider (that is, one not on the standard list
in the CreationPage).

We will attempt to base our solution on the existing upload functionality
in Altinn Studio, where the Editor provides a way to upload an existing data model.
```[tasklist]
### Tasks
- [x] explore Altinn Studio Editor Data Model upload solution
- [x] transfer and test code from Altinn Studio
- [x] the certificate file must be transferred to backend (BFF) : must make special POST request
```

**Comment by Torgeir333** [comment]
The Altinn Studio Model upload code has been located to 
/frontend/app-development/features/dataModelling/SchemaEditorWithToolbar/LandingPagePanel.tsx

**Comment by Torgeir333** [comment]
MaskinportenPage now has a functional button, activated only when requirements are met.
