### ISSUE TITLE
MaskinportenPage set up of Redux maskinportenSlice

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#55]
The MaskinportenPage (or  MaskinportenPageIntAdmPage), 
calls for handling of information (Navn, Beskrivelse) about a new systemUser,
just like CreationPage.

In addition we have the complex issue of uploading a certificate file,
and pushing it to BFF. Possibly BFF should validate the certificate file,
and return some confirmation that the systemUser creation process can 
proceed.

The Redux slice should reflect the circumstances.

We will, as usual, start small and simple, by establishing the Redux Slice,
with just the Navn and Beskrivelse variables.
```[tasklist]
### Tasks
- [x] set up basic Redux slice
- [x] establish Navn and Beskrivelse as Redux variables
- [x] link input boxes to a reducer for Navn and Beskrivelse
- [x] test availabillity of Redux maskinportenPageSlice data
- [ ] establish boolean variables to survey upload process
- [ ] add message to user, saying that certificate has been uploaded (and validated perhaps)
```

**Comment by Torgeir333** [comment]
The basic functionality of the new maskinportenPageSlice is now working.

A remaining question is how this slice should monitor the file upload process from the local machine,
and then monitor the upload of the certificate file to the BFF. 

Quite probably, the Opprett/Create functionality should be blocked until the certificate has been 
transferred to the BFF. At least. 

Now, in our software development, the specifications from external stakeholders is not clear.
Thus we should aim for the lesser target of uploading a TEST certificate, first to the browser, and then
to the BFF. Then BFF should return validated or non-validated somehow.

**Comment by Torgeir333** [comment]
Upload of certificate, with two pairs of metadata, in a Form-object, now works.

We do not yet have a return message from BFF to state that the certificate is recieved (and perhaps validated).
This might be a separate issue.

**Comment by Torgeir333** [comment]
Issue #104 will track progress on surveying the upload process.
