### ISSUE TITLE
Task: API to list systems from system register

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#61]
### Description

The BFF needs to expose a list of systems from the system register. 

### Additional Information

The list will be retrieved from the system register API in authentication component

### Tasks

- [x] Create systemregister controller
- [x] Create list method
- [x] Create mock testdata

### Acceptance Criterias

- [x] BF list all available system from system register
- [x] List include name/description and the system id to be selected when selecting in dropdown
```[tasklist]
### Depends on code in Authentication Comp:
- [ ] https://github.com/Altinn/altinn-authentication/issues/607
```
