### ISSUE TITLE
Task: 9.15 Create SystemRegister APIController

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication-frontend#67]
```[tasklist]
### Tasks
- [x] 9.15.1 Create APIController
- [x] 9.15.2 Create SystemRegisterService
- [x] 9.15.4 Setup RegisteredSystemDTO with Frontend
- [x] 9.15.5 Setup Mock data for SystemRegister
- [x] 9.15.6 Setup Xunit tests for SystemRegister
```

moved these two unfinished task to other Tasks
- [x] 9.15.3 Create SystemRegisterClient with proper integration vs Authentication Component, moved to #69
- [x] 9.15.7 Write good Unit Tests, moved to #166
