### ISSUE TITLE
Task: 9.16 Implement Clients for the BFF towards Altinn Authentication

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#69]
## Acceptance critera
- [x] Client for SystemUser CRUD API service towards Authentication Component
- [x] Client for SystemRegister CRUD API service towards Authentication Component
- [ ] Client for Authentication service
- [x] Client for UserProfile service
- [x] Client for Party service
- [x] Authentication token from user is sent with request
- [x] Implement access token for needed clients

```[tasklist]
### Tasks
```
