### ISSUE TITLE
Task: Establish temporary authentication frontend URL 

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#7]
### Description

We need to establish the authentication frontend URL.

For example, the access management frontend has a base URL of "/accessmanagement/ui", which is part of most requests to this solution.

### Additional Information

The exact URL is something to be decided also by external stakeholders, and is not yet available. 

A temporary solution is to use "/authfront/ui" in the React code. BFF should also make a choice here.
```[tasklist]
### Tasks
- [x] Rebuild the Router solution to use the temporary URL /authfront/ui
- [x] API calls from the React app should also use the new URL
- [ ] when final URL is established all calls and paths must be changed and tested
```

**Comment by Torgeir333** [comment]
We have per 20.09.23 the new Authentication OverviewPage on a new path 
with the new temporary base url 
http://localhost:5173/authfront/ui/auth/overview

**Comment by simen-rekkedal** [comment]
Rune and the team has decided that the URL should be authn.ui.altinn.no
