### ISSUE TITLE
OverviewPage set up Redux overviewPageSlice and fetchOverviewPage API call

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#71]
The OverviewPage at the moment lists two mocked SystemUsers.

We aim to use a list of SystemUsers from the Redux State.

Thus we need to set up the Redux overviewPageSlice,
and populate it with data from the API call to BFF endpoint 
GET /systemuser/0
which returns a mock array of 3 SystemUserObjects.

Unfortunately, the mock data per now reflects the old SystemUserObject,
not the new one with attributes ownedBy and controlledBy 
(see Repo Wiki update of 23.10.23).

```[tasklist]
### Tasks
- [x] Set up overviewPageSlice
- [x] Connect slice to Store
- [x] Set up fetchOverviewPage API call BFF endpoint /authfront/api/v1/systemuser/0
- [x] format data and store in Redux State (must be robust to resist outdated BFF SystemUserObject)
- [x] test using Chrome Redux DevTools
- [x] fixing outdated BFF/Swagger SystemUserObject returned by dialogue with Simen
- [x] re-test new SystemUserObject processing in Redux
```

**Comment by Torgeir333** [comment]
The received SystemUserObject from BFF now contains 6 key:value pairs,
and all 6 are now represented in the systemUserArray in the overviewPage Redux State slice.
