### ISSUE TITLE
Present DTO SystemUserObjects in Redux State in the OverviewPage list of SystemUsers

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#75]
Issue #71 established the OverviewPage Redux slice and the API call to populate the state slice.

Now the new information should be presented in the OverviewPage list of SystemUsers.

So far the mock data on thew OverviewPage have been hard-coded, in addition to
some dynamic demo-data from the CreationPage (a single new SystemUser was
added to the list by hard-coding from CreationPage Redux slice).

```[tasklist]
### Tasks
- [x] Set title (called Navn in CreationPage, not intuitive graphics yet)
- [x] Set systemType (called Selection in CreationPage, actually reflects Software Provider Firm)
- [x] description goes in middle but should perhaps be truncated later
- [x] ownedBy and controlledBy are shown in brackets in SystemType and Description lines
- [x] div list is given key by SystemUser.id
- [x] there might be too much information: will present to Rune and Mette for design considerations
```

**Comment by Torgeir333** [comment]
![Image](https://github.com/Altinn/altinn-authentication-frontend/assets/94476391/dd13ad20-b33f-42be-b2aa-d7c313be04a5)

**Comment by Torgeir333** [comment]
Refinement discussion resulted in yet another iteration of the SystemUserObject,
as Backend, BFF and Frontend (using BFF DTO), would have divergent needs. OK.
So we need another iteration.
