### ISSUE TITLE
CreationPage posting Redux data to SystemUser POST endpoint 

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#77]
So issue #28 deals with the basis for storing CreationPage data in Redux,
while issue #55 dealing with the POST of certificate to BFF,
thus the next POST task would be to post the information from 
the CreationPage to BFF.

Possibly the SystemUser POST endpoint (see Swagger),
is the place to send this object. This has to be investigated 
and discussed.

This is the request object in Swagger per 25.10.23,
to endpoint /authfront/api/v1/systemuser

{
  "integrationTitle": "string",
  "description": "string",
  "selectedSystemType": "string",
  "clientId": "string",
  "ownedByPartyId": "string"
}

Merk! NB! De to siste feltene er nye per 25.10.23, og ikke tilgjengelig
fra CreationPage. Mulig at de må tas fra cookie eller noe.

The response only seems to be Code = 200,
Description = Success ...

I vaguely remember Simen saying that the GET list returned
now would contain the information in the request object. Yes, it does,
and since this was implemented in issue #75,
the testing of the POST request function could be handled
in the Frontend GUI in OverviewPage. There is only one GET
request there, it is not yet dynamic, but Swagger is not affected
by hard reload of the OverviewPage, since it is connected to 
BFF dotnet app, not Vite frontend app. 

OK. The posted data 
from Swagger does appear in the GUI list in Frontend now
(and will until dotnet app is restarted).

```[tasklist]
### Tasks
- [x] Test Swagger endpoint request and response in Swagger
- [x] Build Redux post request function
- [x] test post function against Swagger endpoint
- [x] test post function against Redux
- [x] integrate new post function with main OverviewPage list
```
