### ISSUE TITLE
Establish first Cypress E2E tests

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#87]
As our React app now reliably serves the rudiments of the three user pathways
(CreationPage, MaskinportenPage and DirectConsentPage),
and we have established several GET and POST API calls,
it might be a good time to start setting up Cypress tests.

At first we will only check on availability of API calls,
buttons, navigation and such.

Cypress tests must be run manually, as the initial
steps must go through dotnet app login at
Docker & NginX etc: http://local.altinn.cloud/
(this now works, see Step-by-step How-to in documentation).

```[tasklist]
### Tasks
- [x] Setup of first Cypress test in new Cypress folder
- [x] Verify that test-user is logged in via http://local.altinn.cloud
- [x] Verify navigation to OverviewPage
- [x] Update Wiki Repo og Cypress folder README How-to-use file
- [x] establish config files and Yarn scripts to run Cypress
- [x] Verify navigation to Creationpage
```

**Comment by Torgeir333** [comment]
First Cypress test has been successfully configured and built in the new Cypress folder.

The documentation has been updated in Wiki Repo and the Cypress folder README How-to-use description.

**Comment by Torgeir333** [comment]
Our Cypress E2E tests did run well locally, but the setup proved to be fragile when faced with Cypress component testing, which worked, but somehow interfered with the E2E configuration. 

This has to be debugged.

On the plus side, the Cypress component tests did also work in the Github Runner environment.

**Comment by Torgeir333** [comment]
The first Cypress E2E tests were successful, but now needs to be integrated with components tests in the new issue #105
