### ISSUE TITLE
Task Group: 9.0 BFF for Authentication-Frontend

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication-frontend#9]
### Description

The Authentication-Frontend react SPA needs a backend for frontend (BFF) as an intermediator between the rest of the Altinn APIs, to enable flexibility and isolate those APIs from the frontend concerns.

The extensive data models in the original APIs will be re-mapped to suitable DTOs for the frontend.

Authentication via ID-porten will be handled in a HomeController on the public facing URL: to be decided.

A set of APIs with suitable DTOs for the SPA will be exposed only for the SPA (with tokens) which hold remapped data from the original APIs deeper inside Altinn. This enables a high degree of customizability.

### Tasks

1. Add the Backend (BFF) source folder with initial project structure (no actual code) to the existing SPA repo.
2. Create the HomeController project 
3. Setup the three essential API calls to enable the SPA to be developed without interruption
 - jwt cookie login/refresh
 - respondee
 - user profile'
4. Setup the first business logic API ( to be decided what this should expose of data)
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/10
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/12
- [x] 9.3 Create the Infrastructure projet
- [x] 9.4 Create the core project
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/25
- [x] 9.6 Create the user profile service
- [x] 9.7 Update the README files for both the BFF and the entire Repo including the SPA, also see 9.11
- [x] 9.8 Enable the entire solution to run in a Docker image, using the included DOCKERFILE
- [x] 9.9 See issue #23
- [x] 9.10 See issue #22
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/41
- [x] 9.12 Sette opp localtest repo for å generere test cookie
- [x] 9.13 Implement Application insights in the BFF application
- [x] 9.14 Setup health check endpoint
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/67
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/69
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/166
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/193
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/194
```

```[tasklist]
### External Dependencies
- [ ] #72
- [x] Authentication Component SystemUser API
- [x] Authentication Component SystemRegister API
- [x] AT and TT Environment setup by the Core team
- [x] URL decided for dev, test and prod: authn.ui.altinn.no
```

```[tasklist]
### Bugs and Chores
- [x] dotnet 8
```

**Comment by simen-rekkedal** [comment]
This is both completed and currently being replaced/included into AM's frontend.
