### ISSUE TITLE
Implement fetching software system vendors from API for pull-down menu in CreationPage

### ISSUE THREAD

**Issue by Torgeir333** [Altinn/altinn-authentication-frontend#94]
Issue #67 has now provided a new GET endpoint, 
described both in Swagger, and in issue #8,
so that the pull-down menu in CreationPage, 
showing software vendor systems
available for a new SystemUser.

Thus we will implement a Redux fetch function to GET the data,
and then populate the pull-down menu with the data from Redux State.

```[tasklist]
### Tasks
- [x] Set up a new Redux fetch function in the CreationSlice
- [x] Set up asynchronous listener (ExtraReducer) in CreationSlice to populate Redux State
- [x] test new creationPage Redux State using Chrome DevTools
- [x] Use the new fetch function once when OverviewPage first renders
- [x] Populate pull-down menu with data from Redux State rather than local mock data used so far
```
