### ISSUE TITLE
Configure IpAddress forwarding on the api management and traefikk tool

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication-frontend#97]
### Description

Auditlog requires that we log the client's ipaddress. Right now, we don't have the configuration in the Api Management/traefikk for forwarding the ipadress to the platform components.

### Tasks

- [ ] Configure Apimanagement to forward the ipadress of the client
- [ ] Configure traefikk to forward the ipadress further to the platform components

### Acceptance Criteria

- [ ] Client ipadress is accessible in the platform component via ["X-Real-IP"] or ["X-Forwarded-For"]
